### PR TITLE
Selectable resizing algorithms

### PR DESCRIPTION
**Pull request by kalarepa**
By default Windows uses nearest neighbor. It looks very, very ugly.
I made changes to set default to bilinear (looks way better) and also to allow selection of other algorithms that Windows offers (cubic and fant).
Also, after changes by Daniel (I think) there was namespace inclusion missing (fixed in https://github.com/kalarepa/FFImageLoading/commit/08b53c66bdbb7c2ad7100330e006399c4f6158bf).

### CODE REVIEW

**Comment by molinch** [comment]
@daniel-luberda I let you review this one. I'm not into WP.

**Comment by daniel-luberda** [comment]
@molinch @kalarepa 
Ok, I'll check it soon :) We could definitely change default interpolation to bilinear.

**Comment by kalarepa** [comment]
@daniel-luberda:
I see that you changed DownsampleMode's type from string to InterpolationMode (link: https://github.com/molinch/FFImageLoading/commit/c8aa43911ce93df31466f086110fea4491872df4#diff-a0631007a2c4f1af040bde3df170c18bR311).
While I absolutely agree that this makes nicer code, there's one drawback to it: you can't set DownsampleMode in XAML, like you did in WP8.1 demo, or how I did in UWP demo.
Setting this property in XAML seemed imperative to me - because where else would I set it? Doing so in code-behind seems off to me.

**Comment by daniel-luberda** [comment]
@kalarepa Thanks for the PR. Nice work. 

See this: https://github.com/molinch/FFImageLoading/blob/master/samples/Simple.WinPhone.Sample/MainPage.xaml

Yes, XAML support is a must have for Windows. But I added `DownsampleMode="Bilinear"` and it's working fine. Is UWP different than WinRT in that matter? Could you give me more details?

**Comment by kalarepa** [comment]
@daniel-luberda: I'm without access to my PC, so I can't run it.
But once in some other project I tried to set enum value in XAML and I remember I had issues with it.
Maybe that's just my lack of knowledge.
I'll let you know in a day or two, once I'll be able to access my machine.
BTW, since default setting right now is bilinear, I think it would make more sense to test some other setting - especially nearest neighbor would be easilly distinguishable from others.

**Comment by daniel-luberda** [comment]
@kalarepa Ok. Let me know if it works. Generally, in XAML, all enum values are converted to `int` when building, so it should work just fine. The key part to get it working is to assign `int` values to enum items. 

> BTW, since default setting right now is bilinear, I think it would make more sense to test some other setting - especially nearest neighbor would be easilly distinguishable from others.

Yes, we could put something else there.

**Comment by kalarepa** [comment]
@daniel-luberda: That's what newest Visual Studio tells me:
`MainPage.xaml(39,21): XamlCompiler error WMC0055: Cannot assign text value 'Cubic' into property 'DownsampleMode' of type 'InterpolationMode'`.

**Comment by daniel-luberda** [comment]
Naming is changed: 

	public enum InterpolationMode
	{
		Default = 0,
		None = 1,
		Low = 2,
		Medium = 3,
		High = 4,
	}

**Comment by kalarepa** [comment]
Right, I forgot. Okay, it works! Sorry for the hassle.
But you did break one thing by inserting ConfigureAwait(false) everywhere. I'll do another pull request soon.

**Comment by daniel-luberda** [comment]
@kalarepa 

> But you did break one thing by inserting ConfigureAwait(false) everywhere. I'll do another pull request soon.

Could you give more info? It should work as it was fixed already. Did you synced with repo?

**Comment by kalarepa** [comment]
Sure I could. And yes, I have synced with master branch just 15 minutes ago.

Take a look at FFImage.LoadImage(). In it's original form it crashes at `if (ErrorPlaceholder != null)` line with exception `The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))`.

Apparently, accessing DependencyProperty from worker thread is illegal. So I guess `ConfigureAwait(false)` right by ErrorPlaceholder and LoadingPlaceholder should go. Interestingly enough, one by `await FFImageSourceBinding.GetImageSourceBinding();` doesn't seem to cause problems.

**Comment by kalarepa** [comment]
Also, there's no need to check if `DownsampleMode` is null. It's enum, so it can't be.

**Comment by daniel-luberda** [comment]
Ok, if you send a PR, I'll merge it. Thanks!

**Comment by daniel-luberda** [comment]
BTW: control should be a lot more responsive after some DiskCache (non-blocking) updates.

**Comment by daniel-luberda** [comment]
Merged. Thanks!

**Comment by daniel-luberda** [comment]
I"ll try to make nuget soon

**Comment by kalarepa** [comment]
As for me - there's no hurry. For my project I build my own packages to test the changes in a real app, so I already have newest version :).

**Comment by molinch** [comment]
@kalarepa thanks for the ConfigureAwait.
I can't build Windows stuff so I couldn't really test it.

**Pull request merged**
