### PR TITLE
Transformations fixes

### PR DESCRIPTION
**Pull request by daniel-luberda**
- Unified RoundedTransformation iOS/Android behavior
- fixed iOS CircleTransformation and RoundedTransformation not fitting issue

### CODE REVIEW

**Comment by molinch** [comment]
I think you are aware of it but that does not fix the issue

**Comment by daniel-luberda** [comment]
Look at the rest of commits. It should be fixed.

**Comment by daniel-luberda** [comment]
Does FFImageLoading process transformations when `source = null` ?

**Comment by molinch** [comment]
It shouldn't be the case

**Comment by daniel-luberda** [comment]
Thanks, I was wondering if nulls should be handled inside Transform methods.

**Comment by molinch** [comment]
It's still buggy on iOS though
ios simulator screen shot 07 oct 2015 07 55 44

**Comment by molinch** [comment]
I changed it, it's now easier, we reference ITransformation only. From everywhere.
Therefore iOS issue is still there.

**Comment by daniel-luberda** [comment]
You changes won't work inside Xamarin.Forms PCL project. IFormsTransformation must be platform independent because it must be the same object in iOS and Android.

**Comment by molinch** [comment]
ITransformation is platform independant. In fact it comes from a PCL already.

**Comment by daniel-luberda** [comment]
When you have **the same dll** for Android and iOS UI you must have platform independent instance for that. Try to create Xamarin.Forms PCL project, example is a shared project. Am I missing something?

**Comment by daniel-luberda** [comment]
The same with FFColorMatrix.cs it must be in FFImageLoadin.Forms because it's PCL.

**Comment by molinch** [comment]
Please just wait 20mn. I need to repackage the Nugets. You will see it will work as a charm without IFormsTransformations :)

**Comment by daniel-luberda** [comment]
BTW: The fix for iOS bug is potentially here: 
https://github.com/daniel-luberda/FFImageLoading/commit/a1e151e516fb3970d6e4d5074948fbb17f58dcb3

**Comment by molinch** [comment]
https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/1.1.7-alpha3 this one should work fine even for Xamarin.Forms PCL projects

**Comment by daniel-luberda** [comment]
Try to compile this project. You'll see that you cannot add any transformation. 

https://www.dropbox.com/s/7gtru0b64uwxpgl/FFImageLoadingPCLTest.zip?dl=0

**Comment by molinch** [comment]
Fixed please take new nugets

**Comment by daniel-luberda** [comment]
Tested it. It compiles. 

- without Transformation image is show = OK
- with Transformation image is not shown = NOT WORKING

**Comment by molinch** [comment]
Ok, shouldn't be a big deal to fix it. Could you change the Xamarin.FFImageLoading so it becomes a PCL project instead of a Shared Project?
It would be much easier for me to test & better for testing since PCLs are more restrictive.

**Comment by daniel-luberda** [comment]
> Could you change the Xamarin.FFImageLoading so it becomes a PCL project instead of a Shared Project?

Yes, that's not a big deal. But what about `IFormsTransformation`? Will you restore it?

**Comment by molinch** [comment]
No because it's no longer needed. Each transformation will be invokable from PCL project and they will automatically be replaced by the native implementation using Bait and switch (http://log.paulbetts.org/the-bait-and-switch-pcl-trick/).

**Comment by daniel-luberda** [comment]
Bait & Switch? Just read it. That could definitely be a better solution!

**Pull request merged**
