### PR TITLE
Added new Xamarin.Forms samples

### PR DESCRIPTION
**Pull request by daniel-luberda**

### CODE REVIEW

**Comment by molinch** [comment]
These are great! Thanks @daniel-luberda 

I separated Transformations in a separate Nuget package. It can be referenced from regular projects or Forms projects.
https://www.nuget.org/packages/Xamarin.FFImageLoading.Transformations/

The package should be added both in PCL and Droid & Touch projects. This way Bait & Switch is working.

**Comment by molinch** [comment]
Once you tell me it's working fine on your side I can push a release (not an alpha release).
Then I will also unlist older releases.

**Comment by daniel-luberda** [comment]
Tested it inside few of my projects and it's actually very stable. Previous build had a lot of these: https://github.com/molinch/FFImageLoading/commit/186fcafe6128a3982916f09bfafe7481a9b656ca and https://github.com/molinch/FFImageLoading/commit/a088cf2a09fab0a48a79cc3770ab8e6a5e47b5be

**Comment by molinch** [comment]
Great I will do it tomorrow then

**Comment by highplains** [comment]
I couldn't get the latest alpha nuget to run on a device, pictures and placeholders wouldnt load. Worked ok with the same code in the simulator though... iOS

**Comment by daniel-luberda** [comment]
@highplains Can you give more details or some code?

**Comment by highplains** [comment]
Don't really have a ready repo cause it's part of a production project.

But as far as details...

Xam forms, latest beta release 1.5.1.6455-pre1
Xcode 7
ios 6s simulator
test device iphone 6+

Simulator loads up nice, cool fade in on picture load too. Fresh install on
the device and the image is just black, no placeholders are anything. Did
restarts, cleans, wipe the obj and bin folders and still nada.

Was the alpha tested on actual devices as well as simulators?

**Comment by molinch** [comment]
Thanks for the feedback @highplains 
I will have a look

**Comment by molinch** [comment]
@highplains On my side with, an iPhone 5S, XCode 7/SDK9, it works fine. I tested debug and release no problem at all.

Are you sure you correctly referenced the nuget packages in all your projects? PCL, Droid, Touch?

**Comment by daniel-luberda** [comment]
It also works fine to me on devices. 

BTW: @molinch Do you think we should check if animation is started at UI thread here: https://github.com/molinch/FFImageLoading/blob/6111457ca0976657f26fec84e8295357f793b684/FFImageLoading.Touch/TaskParameterExtensions.cs#L42 ?

**Comment by molinch** [comment]
DoWithImage is always invoked on UI thread so you don't need to do anything :)
https://github.com/molinch/FFImageLoading/blob/6111457ca0976657f26fec84e8295357f793b684/FFImageLoading.Touch/Work/ImageLoaderTask.cs#L112

**Comment by daniel-luberda** [comment]
Thanks! That was my concern about iOS animation :) (I though it could be the case, why it's not working on device for @highplains)

**Pull request merged**
