### PR TITLE
Windows 10 improvements

### PR DESCRIPTION
**Pull request by kalarepa**
Okay, here's another version. I haven't tested everything though.
Thank you guys for this awesome library. I've been looking for something like this for months. I tried even writing my own library, but it sucks terribly comparing to what you've done. Thanks a lot. I hope didn't break anything in those commits.

### CODE REVIEW

**Comment by daniel-luberda** [comment]
Very nice! I added some modifications to you PR, look here: https://github.com/molinch/FFImageLoading/tree/pr/96

@kalarepa @molinch What do you think?

**Comment by daniel-luberda** [comment]
BTW: @molinch Should we implement auto image reload in Xamarin.Forms `CachedImage` when `Transformations` list changes? Currently, it doesn't do that.

**Comment by daniel-luberda** [comment]
Sorry, wrong button :)

**Comment by molinch** [comment]
@daniel-luberda In my opinion altering transformation list is not really useful in a real world app.
Anyway people can still do what you propose via Invalidate methods. Isn't it enough?

**Comment by daniel-luberda** [comment]
In Forms, there's no `Invalidate` method which reloads transformations (it's really a `View` derivative which invalidates layout measures). 

The only currently available solution is to set source to `null` first, then reapply the previous source if the same source is used.

**Comment by molinch** [comment]
I'm talking about ImageServie.Invalidate methods

Le lundi 21 décembre 2015, Daniel Luberda <notifications@github.com> a
écrit :

**Comment by molinch** [comment]
So what you propose is just to nullify Source and reload data?

**Comment by daniel-luberda** [comment]
It's another situation. It has nothing to do with cache invalidation. 

- We have an image with source "something.png" without transformation
- We change `Transformations` to eg. CircleTransformation
- Currently image is not reloaded at all
- The only current solution to reload it and maintain the same url is to set source to null and reapply the previous one.

**Comment by molinch** [comment]
Ok! Sorry I misread what you wrote initially.
Fair enough, looks like a good idea.

**Comment by daniel-luberda** [comment]
@molinch Ok :) I'll check on this later. 

BTW: https://github.com/molinch/FFImageLoading/commit/85d0234eb0dfd60cb8f306ef942605d77d8c6352
https://github.com/molinch/FFImageLoading/commit/a1e7f976030a940a086adcaab0b7e03710349586

Is it ok to change interface method? Should we leave it?

**Comment by molinch** [comment]
It's no problem to change IImageLoaderTask interface and ImageLoaderTaskBase.
Anyway all that is hidden to the user, he will go though Fluent API.

**Comment by kalarepa** [comment]
I think I broke something. Now when you have multiple FFImages visible on a page and just one of them has Transformations set, those transformations are used for all images.
BTW, https://github.com/molinch/FFImageLoading/commit/0325ab411525015e61e1622c9bb071da2a0fdcba - this is really sweet.

**Comment by kalarepa** [comment]
Another thing popped to mind - in LoadFromStreamAsync() (from file ImageLoaderTask.cs.cs - BTW, why double .cs?) you use some trickery in try-catch block, because in C#5 you couldn't await in catch block. Now with C#6 you can. Perhaps it'd be possible to use that new ability and to clean up a little bit.

**Comment by molinch** [comment]
Yes this was for C#5 support. Now that C#6 is well supported this part can be changed.

**Comment by kalarepa** [comment]
I fixed the issue I had.
All that needs adding is this line in FFImage constructor:
Transformations = new List<ITransformation>();

So, what about async transformations? Do you think it's currently possible?

**Comment by daniel-luberda** [comment]
I wouldn't change current Transformations implementation, users use a lot of custom transformations and we can't break anything in that matter. What we could do is add another interface `ITransformationAsync` which support async. Then we could simply try to check the type and handle it with appropriate logic.

**Comment by daniel-luberda** [comment]
> All that needs adding is this line in FFImage constructor:
> Transformations = new List();

I'll add it.

**Comment by molinch** [comment]
> BTW, why double .cs?
Good catch it's a naming mistake. File should be renamed :)

**Comment by daniel-luberda** [comment]
Renamed: https://github.com/molinch/FFImageLoading/commit/d5f42dbde80115d1ffa7109fa728ac985d95c4fa
Fixed: https://github.com/molinch/FFImageLoading/commit/7f934348ffbefb7f923ed148ff8f9635d84914e6

**Comment by daniel-luberda** [comment]
> BTW, why double .cs?) you use some trickery in try-catch block, because in C#5 you couldn't await in catch block. Now with C#6 you can. Perhaps it'd be possible to use that new ability and to clean up a little bit.

I'll create an issue for that

**Comment by daniel-luberda** [comment]
I think this branch could be merged with master. @molinch What do you think?

**Comment by molinch** [comment]
Yes I agree

**Comment by daniel-luberda** [comment]
I added some updates here: https://github.com/molinch/FFImageLoading/tree/pr/96 (including Xamarin.Forms TransformPlaceholders support. Will you merge it too? Or should I do it?

**Comment by kalarepa** [comment]
Thanks for pushing those changes to master. I feel flattered :).

**Comment by daniel-luberda** [comment]
@kalarepa Thanks to you, collaboration is welcomed, especially on Windows which was added recently, It was quite a lot of work, so some things may appear, as always when something is new. I also don't use pure UWP a lot, I prefer Xamarin.Forms, so `FFImage` control was added in hope someone would test it heavily.

**Pull request merged**
