### PR TITLE
Add detail activity with shared element transition

### PR DESCRIPTION
**Pull request by c1rus**

### CODE REVIEW

**Comment by c1rus** [comment]
There is still this problem. when you go back from detail activity, sometimes the images looks like this:

**Comment by molinch** [comment]
Hi @c1rus I'm looking at it. Will try to find what happens

**Comment by c1rus** [comment]
hi, thx...

there is bug in DetailActivity, placeholders should be loaded from ApplicationBundle.

Maybe thanks to that, I have seen this error couple of times:

```
Android.Util.AndroidRuntimeException: Only the original thread that created a view hierarchy can touch its views.
  at at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x0004b>
  at at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) <IL 0x00006, 0x0003b>
  at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
  at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
  at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71
  at at (wrapper dynamic-method) object.f707769a-68ec-4070-940e-df80042175d8 (intptr,intptr) <IL 0x00011, 0x00027>
  at --- End of managed exception stack trace ---
  at android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
  at at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6247)
  at at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:902)
  at at android.view.ViewGroup.invalidateChild(ViewGroup.java:4637)
  at at android.view.View.invalidateInternal(View.java:11690)
  at at android.view.View.invalidate(View.java:11654)
  at at android.view.View.invalidate(View.java:11638)
  at at android.widget.ImageView.setImageDrawable(ImageView.java:456)
```

Do you think that PrepareAndTryLoadingFromCacheAsync is causing it?

**Comment by molinch** [comment]
Yep, that's already fixed in https://github.com/molinch/FFImageLoading/commit/1037aab985c0fa3580e548c39f568575cddbb926

**Comment by molinch** [comment]
Btw, even when using a standard ImageView I have the issue with wrong image frame/position.
I will continue investigating

**Comment by molinch** [comment]
Looks like there are many bugs with transitions, images but also RecyclerView.
For example:
https://code.google.com/p/android/issues/detail?id=74665
http://stackoverflow.com/questions/26717515/weird-issue-when-transitioning-imageview-in-android-5-0
:-(

**Comment by c1rus** [comment]
grr :( btw i get the same result without transitions, just change to this in PictureAdapter.

```
ImageService.LoadUrl("http://files.usvit.alejtech.eu/peto/6480947_xl.jpg")
   .Retry(3, 200)
   .DownSample(100, 100)
   .LoadingPlaceholder(Config.LoadingPlaceholderPath, FFImageLoading.Work.ImageSource.ApplicationBundle)
   .ErrorPlaceholder(Config.ErrorPlaceholderPath, FFImageLoading.Work.ImageSource.ApplicationBundle)
   .Into(vh.Image);
```

**Comment by c1rus** [comment]
btw i tried it with picasso and it works. :/

**Comment by molinch** [comment]
We rely on TransitionDrawable (for fading) and Picasso doesn't.
TransitionDrawable seems to be very sensitive about Drawables having different sizes...
When I remove the TransitionDrawable then everything is fine... I guess we'll need to try to do it like in Picasso: https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/PicassoDrawable.java
They implement the fading effect in their Drawable.

**Comment by c1rus** [comment]
good job, you found the problem...  i was also trying, but with no luck, thx :)

**Comment by molinch** [comment]
An attempt to reproduce what Picasso does for fading: https://github.com/molinch/FFImageLoading/commit/c2ff05be9200b5e9cafc542349f7a512742442a7

It solves the issue you had

**Comment by c1rus** [comment]
awesome!

**Pull request merged**
