### PR TITLE
UWP improvements

### PR DESCRIPTION
**Pull request by kalarepa**
I fixed an issue where entire UI would freeze on Windows 10. I tested it on Windows Phone 8.1 and it doesn't seem to break anything.
I added simple UWP project. It helped me debug the problem I had, perhaps it will help others too.

### CODE REVIEW

**Comment by molinch** [comment]
@kalarepa Why did you close it? It's not an issue in the end?

**Comment by kalarepa** [comment]
Looking closer, there are more things that need fixing. I'll do my best and reopen later.

**Comment by molinch** [comment]
Ok many thanks for your help!

**Comment by daniel-luberda** [comment]
I haven't tested it on Windows 10 yet. But the `bitmap.SetSourceAsync` should definitely be preferred over `bitmap.SetSource`. What are the other issues you're experiencing?

**Pull request closed without merging**
