### PR TITLE
Windows Silverlight 8.1 support

### PR DESCRIPTION
**Pull request by PaulAchess**
boom.

### CODE REVIEW

**Comment by PaulAchess** [comment]
Damn, I think I've done everything on master. This is my first pull request, I'm sorry for this. If this is a problem I could use some help.

**Comment by molinch** [comment]
Thanks :+1: 
Don't worry we can review the PR as a separate git branch.

**Comment by molinch** [comment]
My first question after seing so many files added: couldn't some of these be shared between Windows and Windows Silverlight?
@daniel-luberda maybe you can review this better than me :)

**Comment by PaulAchess** [comment]
Unfortunately I was a bit brutal on my support yes.

I am not used to work with Shared projects, and I had a lot of minor troubles to support both platform, which usually have only slight differences.

I was afraid to break the existing code and that is why I choose not to touch to it, at least for the first commit.

There is still room for improvement and I would gladly help to improve this later on.

**Comment by daniel-luberda** [comment]
@PaulAchess @molinch A lot of files can be shared. We don't have to use shared project but we could just link files instead as I did for Windows (eg. DownloadCache implementation is a linked file). 

I can review it in in a few days.

**Comment by PaulAchess** [comment]
Okay it was clearly waaaaay easier to use existing files once it was done. Indeed, many files were duplicates.

I'm not a big fan of compilation symbols but it was appropriate here, more than 90% of the code was shared.

The review should not take long now :)

**Comment by daniel-luberda** [comment]
Ok, I'll try to merge it ;) Thanks! Compilation symbols are must have here. It would be a pain to fix every issue in two files in the future :)

**Comment by PaulAchess** [comment]
+1, that's clearly better here.

**Comment by daniel-luberda** [comment]
@PaulAchess As you see it's merged. Thanks once again.

**Comment by molinch** [comment]
:+1:

**Comment by PaulAchess** [comment]
Amazing! Thank you very much!

**Pull request merged**
