### PR TITLE
Fix memleak: dispose of CancellationTokenSource

### PR DESCRIPTION
**Pull request by sebastian-frysztak**
Hi, this is @kalarepa.
While profiling memory usage of my app I found that `CancellationTokenSource` and `TimerQueueTimer` are leaking memory. Turns out, both are related and disposing of `CancellationTokenSource` remedies the issue.
I added new sample that helped me identify the problem.

On a unrelated note, I have a question. I remember @daniel-luberda changing disk cache folder to TemporaryFolder. Do I have to manually clean old folder in LocalFolder?

### CODE REVIEW

**Comment by sebastian-frysztak** [comment]
There's also one CTS in ImageLoaderTask.cs, although I'm not sure when to dispose it.

**Comment by daniel-luberda** [comment]
Thanks for a PR!

> On a unrelated note, I have a question. I remember @daniel-luberda changing disk cache folder to TemporaryFolder. Do I have to manually clean old folder in LocalFolder?

@sebastian-frysztak No, the old one is not removed automatically, FFImageLoading will only use new temporary folder location and create a journal file from scratch, so all previously cached items would be recreated.

**Comment by sebastian-frysztak** [comment]
OK, this latest commit sometimes makes app crash here https://github.com/sebastian-frysztak/FFImageLoading/blob/ec3b3dd62eeb388ca0bb8d9c5c6e0944cf38f764/source/FFImageLoading.Shared/Work/ImageLoaderTaskBase.cs#L117 . We'll have to find some other way to dispose of CTS. What really sucks is that `IsDisposed` property is private.

@daniel-luberda: so which directory do I remove?

**Comment by molinch** [comment]
Are you sure they aren't disposed automatically by the GC?
http://stackoverflow.com/questions/6960520/when-to-dispose-cancellationtokensource

**Comment by sebastian-frysztak** [comment]
I know that different people have different opinions. [MSDN](https://msdn.microsoft.com/en-us/library/dd997364.aspx?f=255&MSPPError=-2147217396) says those should be disposed:
> The CancellationTokenSource class implements the IDisposable interface. You should be sure to call the CancellationTokenSource.Dispose method when you have finished using the cancellation token source to free any unmanaged resources it holds.

In case of DownloadCache disposing is not a big deal - it's just a `using` block.

**Comment by daniel-luberda** [comment]
http://blogs.msdn.com/b/pfxteam/archive/2012/03/25/10287435.aspx

**Comment by sebastian-frysztak** [comment]
That article talks about disposing Tasks. Tasks in Windows Runtime are not disposable.
Could you please let me know what was old directory for cache? I want to create UpdateTask to remove it automatically.

**Comment by daniel-luberda** [comment]
Sorry, pasted wrong thing: 

> I didn't think any of the current answers were satisfactory. After researching I found this reply from Stephen Toub ([reference](http://blogs.msdn.com/b/pfxteam/archive/2012/03/25/10287435.aspx)):

> It depends.
> In .NET 4, CTS.Dispose served two primary purposes.  If the 
> CancellationToken's WaitHandle had been accessed (thus lazily
> allocating it), Dispose will dispose of that handle.  Additionally, if
> the CTS was created via the CreateLinkedTokenSource method, Dispose
> will unlink the CTS from the tokens it was linked to.  In .NET 4.5,
> Dispose has an additional purpose, which is if the CTS uses a Timer
> under the covers (e.g. CancelAfter was called), the Timer will be
> Disposed. 

>It's very rare for CancellationToken.WaitHandle to be used,
> so cleaning up after it typically isn't a great reason to use Dispose.
> **If, however, you're creating your CTS with CreateLinkedTokenSource, or
> if you're using the CTS' timer functionality, it can be more impactful
> to use Dispose.**

> The bold part I think is the important part. He uses "more impactful" which leaves it a bit vague. I'm interpreting it as meaning calling `Dispose` in those situations should be done, otherwise using `Dispose` is not needed.


**Old cache folder: `ApplicationData.Current.LocalFolder` https://github.com/molinch/FFImageLoading/commit/94d2492f8553f45c78ef34da02e62cc8dde70845**

**Comment by sebastian-frysztak** [comment]
We have exactly the situation he's talking about: both timer and CreateLinkedTokenSource (https://github.com/sebastian-frysztak/FFImageLoading/commit/2959c978ca97c77a6b0da6cd74390c4ab578cd11).

But when it comes to ImageLoadingTask - I'm not that familiar with FFImageLoading to figure out when to dispose. [This](https://github.com/sebastian-frysztak/FFImageLoading/commit/ec3b3dd62eeb388ca0bb8d9c5c6e0944cf38f764) is not a good place, like I said earlier. I guess we could just let it be and don't dispose in this situation. CTS doesn't use a timer or CreateLinkedTokenSource in this place, as far as I can tell.

**Comment by molinch** [comment]
Why is it not a good place ? https://github.com/sebastian-frysztak/FFImageLoading/commit/ec3b3dd62eeb388ca0bb8d9c5c6e0944cf38f764

**Comment by sebastian-frysztak** [comment]
Sometimes, `Cancel()` is called after `Dispose()`, and that leaks to a crash.

**Comment by molinch** [comment]
Many thanks @sebastian-frysztak I created a branch for it https://github.com/molinch/FFImageLoading/tree/fix-token-leak

I will add your changes and a few other so Disposing the CTS won't cause issues

**Comment by sebastian-frysztak** [comment]
I'm glad I could help :).

**Comment by molinch** [comment]
Merged into master :)

**Comment by sebastian-frysztak** [comment]
Great, thanks!

**Pull request merged**
