### PR TITLE
Forms improvements

### PR DESCRIPTION
**Pull request by daniel-luberda**
- Some refactorings
- Both Path and Application resources now work when using FileImageSource (https://github.com/daniel-luberda/FFImageLoading/commit/a88e6f7fb3c6104f2846083ee97b47d94ef18da3#commitcomment-13977928)
- Added CornersTransformation (you can transform each corner of image separately)
- Samples improvements (better main menu, transformations updates)

### CODE REVIEW

**Comment by molinch** [comment]
Regarding loading from Streams I need to think a bit.
It's not particularly difficult but we may need to add some options like: AutomaticallyClose, DontClose

**Comment by daniel-luberda** [comment]
@molinch I could also handle streams only on the Forms renderer side. What do you think?

**Comment by molinch** [comment]
I don't see how you could handle it just from Forms renderer side? you have some ideas?

**Comment by daniel-luberda** [comment]
@molinch Yes, it's actually quite simple. I'll just mimic Forms Image stream handling. There's also a side effect - cache is bypassed (stream goes straight to the Bitmap or UIImage), but if you'll help me how to get / put streams into the cache we could improve that.

**Comment by molinch** [comment]
Mmmh it's a .NET Stream right? If yes then there's definitely something I don't understand: ImageService, right now, only allows you to load from file, url, assets or resources. So how would you do?

**Comment by daniel-luberda** [comment]
Yes, pure .NET stream. I would bypass ImageService for streams (which would be null) and set image directly to a view.

**Comment by molinch** [comment]
ahhhh I see so bypassing the cache & transformations, now I get it :-)

**Comment by daniel-luberda** [comment]
What do you think? Which is better? :)

**Comment by daniel-luberda** [comment]
BTW: I have almost working implementation for a CropTransformation. It could be useful for setting own avatars (with zoom in and swipe gestures support). Will we be able to add a method to get actual image after transformations as a stream or byte array? With this the image could be saved to database after user interaction.

**Comment by molinch** [comment]
We could have a callback that gives the final bitmap that was displayed. Would that help?

**Comment by daniel-luberda** [comment]
Yes. That would be cool. If I'll have that I could add a sample with AvatarImage cropping then.

**Comment by daniel-luberda** [comment]
> ahhhh I see so bypassing the cache & transformations, now I get it :-)
Don't you think it would be nicer to have a LoadFromStream method? So you can still benefit from cache & transformations?

Actually transofrmations also could be handled manually. It would a lot nicer to have LoadFromStream. Can you lead me where should I look first to add it?

**Comment by molinch** [comment]
Basically TaskParamater, ImageService and ImageLoaderTask.
But if you have 2/3 days to wait then I can implement it too :)

**Comment by daniel-luberda** [comment]
Ok, it could be really cool if you would implement that. I'll wait :)

**Comment by molinch** [comment]
Are you able to provide a key for the Stream? Otherwise caching is pointless.

**Comment by daniel-luberda** [comment]
Actually, we could omit memory cache for now. I don't think it would be very useful. I'll check tommorow if I could get a key for streams.

**Comment by molinch** [comment]
LoadFromStream is added now (in git only): https://github.com/molinch/FFImageLoading/commit/65396eacf85e3ea843ce372205f970eef2e4a16a

**Pull request merged**
