### PR TITLE
Swipe gallery sample

### PR DESCRIPTION
**Pull request by c1rus**

### CODE REVIEW

**Comment by c1rus** [comment]
ok my first pull request. i wanted to separate the sample and transformations, but i didn't make it. :)
Transformations are now without caching.

**Comment by molinch** [comment]
That is really awesome!
I will test it, make an iOS implementation for the Transformation and also add use the caching key.

With your implementation it will always cache the transformed image but with the wrong key. Which means that if you request the image without transformation you might end up with the transformed one.

**Comment by c1rus** [comment]
i think in the DiskCache TryGetStream is a bug, fix:

https://github.com/c1rus/FFImageLoading/commit/236e3180d57fc56836fe26a659d909a29ed68477

**Comment by c1rus** [comment]
i wanted to implement the cache stuff too, but i got stuck on this line:
```
ImageCache.Instance.Add(sourcePath, drawable);
```

now i see that ImageLoaderTask has a Key property. :)
the 'sourcePath' parameter should be 'Key', right?

One question:
The original bitmap will be saved to diskcache and the transform bitmap will be cached to memory, am i right?

**Comment by molinch** [comment]
Yes that's exactly the idea: original bitmap should be saved to disk whereas the transformed one should only remain in LRU cache

**Comment by molinch** [comment]
Thanks for the DiskCache bugfix ! It is coming from the change in issue #6 to allow loading large asset

**Comment by c1rus** [comment]
i like the idea. pull request is created.

**Comment by molinch** [comment]
Are you inline with the changes?

**Comment by c1rus** [comment]
awesome, thanks.

Will you publish the new version on nuget?

Few notes on transformations:
```
ImageCache.Instance.Add(sourcePath + TransformationsKey, drawable);
```

1. I still think that key should be created on one place. Maybe instead of 'Key' property, create a method 'GetKey' which will take path as parameter. 

2. I don't understand why the extra abstraction was need - TransformationBase, BitmapHolder, IBitmap. No code is shared across plaforms. 

Do you think that it would be possible to have method which will calculate DownSampleSize based on ImageView bounds?

**Comment by molinch** [comment]
Thanks for the feedback

1. if you submit a PR I am happy to look at what you propose

2. This was needed since TaskParameter is cross platform. It could not contain a list of Itransformation which has methods accepting/returning Android Bitmap.
If you take your PR and try to compile iOS project you will quickly understand.

Having a possible Fit() method, like with Picasso would be a nice addition. It might be tricky to cover all corner cases tough: imageview size needs to be retrievable and we should take care about screen density too.

**Comment by c1rus** [comment]
thanks for fast response and explanation :) PR submitted, it's just a little change.

**Pull request merged**
