### PR TITLE
Added multiplatform transformation support (including Forms), Fixed SetImage called twice in Forms renderers

### PR DESCRIPTION
**Pull request by daniel-luberda**
Available transformations:
- RoundedTransformation
- CircleTransformation
- GrayscaleTransformation

Samples and screenshots included.

### CODE REVIEW

**Comment by daniel-luberda** [comment]
https://forums.xamarin.com/discussion/52500/bindableproperty-of-imagesource-type-raises-propertychanged-twice-in-custom-views

**Comment by molinch** [comment]
Bugzilla: https://bugzilla.xamarin.com/show_bug.cgi?id=34531

**Comment by molinch** [comment]
Thanks @daniel-luberda !
In the transformations could you dispose/recycle the source on Android? and maybe only dispose it on iOS?

Also in files like TransformationExampleViewModel.cs we have a lot of code commented. Can't we just delete it?

**Comment by daniel-luberda** [comment]
Hi, it is disposed on iOS and Android. Look eg. https://github.com/daniel-luberda/FFImageLoading/blob/master/FFImageLoading.Droid/Transformations/CircleTransformation.cs#L22 line 22 
I wanted it here, because some effect may be build from multiple transformations.

**Comment by daniel-luberda** [comment]
> I wanted it here, because some effect may be build from multiple transformations and without it, it won't be possible to use disposed bitmap.

Already deleted it: https://github.com/daniel-luberda/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/FFImageLoading.Forms.Sample/ViewModels/TransformationExampleViewModel.cs

**Comment by molinch** [comment]
You are right :+1:  I looked a previous commit.

**Comment by molinch** [comment]
Could you explain the fix for Forms ? I woud like to understand prior to commit it

**Comment by daniel-luberda** [comment]
Yes sure, 

- Fix for bug: https://bugzilla.xamarin.com/show_bug.cgi?id=34531 - If ImageSource is the same as previous it ignores it
- Previous CachedRenderer inherited from Xamarin.Forms Image class. I changed it to be a generic View (it's build just the same as Image class). That way we have more control (in Image class, Source property is also handled there, we don't need that - it can lead to additional unexpected results)

**Comment by molinch** [comment]
Thanks for the explanation.

There is just one thing I am not happy to merge it is https://github.com/daniel-luberda/FFImageLoading/blob/master/FFImageLoading.Forms.Droid/TransformationBinding.cs

The original idea was that anybody can add custom transformations. With that it is no longer the case: you can only add what is shipped with the Nuget package. We should rethink that part, each IFormsTransformation should bring his native implementation. We should not have a factory class.

**Comment by daniel-luberda** [comment]
I'm not happy with it either. Do you have an idea how could we implement it? Some initialization method? Dependency injection?

**Comment by daniel-luberda** [comment]
We could have some effects build in and the additional could be initialized with some Register method.

**Comment by daniel-luberda** [comment]
Maybe something like this: IFormsTransformation, IDroidFormsTransformation, ITouchTransformation and CachedImageRenderer.RegisterTransformation(IDroidTransformation nativeTransformation, IFormsTransformation formsTransformation)? But what about constructors parameters? How to pass from Forms to Native?

**Comment by molinch** [comment]
We already had a similar issue when implementing transformations. There is a BitmapHolder for iOs and Android which can give native Bitmap/UIImage: https://github.com/molinch/FFImageLoading/blob/fcbc7cfbac4eec930f2cea8473ffe46f9675fb82/FFImageLoading.Droid/Work/BitmapHolder.cs and https://github.com/molinch/FFImageLoading/blob/fcbc7cfbac4eec930f2cea8473ffe46f9675fb82/FFImageLoading.Touch/Work/BitmapHolder.cs

The extension method is only use in ImageLoaderTask.

**Comment by daniel-luberda** [comment]
Didn't know about that. I think it'll be good for Forms too. We could then make a CachedRenderer.RegisterTransformation(BitmapHolder tranformation) and that's all. What method in ImageLoaderTask adds BitmapHolder transformations?

**Comment by molinch** [comment]
This is how we add a transformation:
https://github.com/molinch/FFImageLoading/blob/bc2d039f2d193974c17740fe8977419777193ec5/FFImageLoading.Common/Work/TaskParameter.cs#L130

The idea is to add an ITransformation to the TaskParameter, TaskParameter is common for iOS and Android, and the class that implements ITransformation has the native code for the transformation.

**Comment by daniel-luberda** [comment]
Ok, now I understand how it's working. Should those pre defined transformations be registered automatically in CachedRenderer.Init() method?

**Comment by molinch** [comment]
That would be a great idea yeah

**Comment by daniel-luberda** [comment]
Didn't know how to handle parameters passing with BitmapHolder, so I added IMultiplatformTransformation interface (IFormsTransition implementation must be platform independent). Take a look at: https://github.com/daniel-luberda/FFImageLoading/commit/81ee8fe58b088dc128f69790f3488b6140634fc2

**Comment by daniel-luberda** [comment]
Steps to Add a custom Transformation: 

- Create `IFormsTransformation` implementation (It's used in Xamarin.Forms UI code)
- Create `IMultiplatformTransformation` implementation for every platform
- Register `IMultiplatformTransformation` implementation with `CachedRenderer.RegisterTransformation(typeof(YourIFormsTransformationImplementation), new YourIMultiplatformTransitionImplementation);`

**Comment by molinch** [comment]
@daniel-luberda It is merged, I changed a few things: we only have ITransformation and transformations are safer.

Two things I would like to fix though:
* On iOS the Circle transformation is strange: circle is bigger than the image size
* I still don't think we need the extra parameters methods for transformations. IMO this should be done in the transformation constructor only.

**Comment by daniel-luberda** [comment]
@molinch Ok, that's great. 

> It is merged, I changed a few things: we only have ITransformation and transformations are safer.
ok! 

> On iOS the Circle transformation is strange: circle is bigger than the image size
I'll check that. 

> I still don't think we need the extra parameters methods for transformations. IMO this should be done in the transformation constructor only.

Do you have an idea how could we instantiate platform specific transformation from FormsTransformation instance? How to pass constructors from forms to native? Forms transformations must be platform independent. What comes to my mind is reflection... but it's quite an ugly solution. What do you think?

**Comment by molinch** [comment]
Let me some time to think about it. I'm sure a nice solution can be found :)

**Comment by daniel-luberda** [comment]
Ok :) I'll think about it too. Can we update Forms nuget for tests? On 1.1.7-alpha1 I'm getting a lot of these: https://github.com/daniel-luberda/FFImageLoading/commit/186fcafe6128a3982916f09bfafe7481a9b656ca

**Comment by daniel-luberda** [comment]
> On iOS the Circle transformation is strange: circle is bigger than the image size

There's a problem with current transformations handling. It only modifies original Bitmap. It doesn't know about image View size and AspectRatio mode. Could we modify transformations to pass this information to transformations?

**Comment by molinch** [comment]
I don't think that should be part of the Transformation. It should work at Bitmap level and should not care about other things.

That's exactly how it is implemented in other libraries like Picasso.
Btw on Android the transformation works fine so it's definitely something to fix in the transformation IMO

**Comment by daniel-luberda** [comment]
I already fixed it. Actually Android Rounded transformation also had an issue (fixed too). See: https://github.com/molinch/FFImageLoading/pull/48

**Comment by daniel-luberda** [comment]
The issue is we're operating on bitmaps. Transformation doesn't know the image view size and aspect ratio, so we can't resize the bitmap to fit the control. It only "rounds" the original image, which doesn't fit inside image control view (bot on android and ios)

**Comment by daniel-luberda** [comment]
I still encourage to provide at least image view size in transformations :) It would allow to add very nice effects which now could not be implemented at all.

**Comment by molinch** [comment]
If image is too big it's the duty of the ImageView to resize it to fit.

I'm sorry but we should not pass the ImageView into the game. The lib is about manipulating/dealing with images, if we want effects at view level then it's not the lib's duty

**Comment by daniel-luberda** [comment]
```
var image = new CachedImage() {
	WidthRequest = 200,
	HeightRequest = 200,
	DownsampleHeight = 200,
	TransparencyEnabled = false,
	Aspect = Aspect.AspectFill,
	CacheDuration = TimeSpan.FromDays(30),
	RetryCount = 3,
	RetryDelay = 500,
	LoadingPlaceholder = "loading.png",
	Transformations = new List<IFormsTransformation>() {
		new GrayscaleTransformation(),
		new RoundedTransformation(40),
	}
};
```
nexus 4 lollipop screenshot 1

**Comment by daniel-luberda** [comment]
> If image is too big it's the duty of the ImageView to resize it to fit.
> 
> I'm sorry but we should not pass the ImageView into the game. The lib is about manipulating/dealing with images, if we want effects at view level then it's not the lib's duty

I understand your design decision. BTW: fixed not fitting issue on iOS here: https://github.com/daniel-luberda/FFImageLoading/commit/d8c078096a7c68d4695c46e1eaf073f1ca096d81

**Pull request merged**
