### PR TITLE
Converted Xamarin.Forms sample to PCL

### PR DESCRIPTION
**Pull request by daniel-luberda**

### CODE REVIEW

**Comment by molinch** [comment]
Hi @daniel-luberda there are some conflicts could you fix them ? Then I can easily merge this and fix the transformations :)

**Comment by daniel-luberda** [comment]
Done, didn't add any references for FFImageLoading in PCL project. Should we reference a nuget? Or a project?

**Comment by molinch** [comment]
Many thanks @daniel-luberda 
Don't worry, now it will be much easier for me to fix PCL stuff

**Comment by molinch** [comment]
Could you try this Nuget package: https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/1.1.7-alpha5 ?
We should a working solution with Bait & Switch now

**Comment by daniel-luberda** [comment]
It's working good! I made some additional samples. I'll make a commit in a few minutes.

**Pull request merged**
